### ISSUE TITLE
[BUG] Enabling `compact` breaks `no_std`

### ISSUE THREAD

**Issue by becominginsane** [Alexhuszagh/rust-lexical#69]
## Description

The current version (v0.8.2) of `lexical-core` claims to be `no_std` (when default features are disabled), and doesn't include any mention of needing `std` in the context of the `compact` feature, but when enabling said feature, compilation is halted because `std` seems to be required by `lexical-util` whose `std` feature was enabled somewhere in the dependency tree.

```
   Compiling lexical-util v0.8.1
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not support the standard library
  = note: `std` is required by `lexical_util` because it does not declare `#![no_std]`
```

## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version: 1.53
- lexical-core version: 0.8.2
- lexical compilation features used: "compat"

## Test case

```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["becominginsane <francesco@zondax.ch>"]
edition = "2018"


[dependencies]
lexical-core = { version = "0.8", features = ["compact"], default-features = false }
```

```rust
fn main() {
    println!("you won't compile me");
}
```
