### ISSUE TITLE
[BUG] consecutive_digit_separator has no effect

### ISSUE THREAD

**Issue by dubrowgn** [Alexhuszagh/rust-lexical#96]
## Description

First, thanks for the great library!

Perhaps I am doing this wrong, or misunderstanding what the flag is supposed to do, but it appears that `consecutive_digit_separator` has no effect on the results of parsing. Setting it to `false` still allows multiple consecutive digit separators in the source string.

## Prerequisites

- Rust version: `rustc 1.68.0 (2c8cc3432 2023-03-06)`
- lexical version:
  lexical-util v0.8.5
  lexical-parse-integer v0.8.6
  lexical-parse-float v0.8.5
  lexical-core v0.8.5
  lexical v6.1.1
- Cargo.toml
```toml
[dependencies.lexical]
default-features = false
features = [ "parse-floats", "parse-integers" ]
version = "6.x"

[dependencies.lexical-parse-integer]
default-features = false
features = [ "format", "power-of-two" ]
version = "x"

[dependencies.lexical-parse-float]
default-features = false
features = [ "format", "power-of-two" ]
version = "x"
```

## Test case

```rust
let opts = lexical_parse_float::Options::new();
const FMT: u128 = NumberFormatBuilder::new()
	.digit_separator(num::NonZeroU8::new(b'_'))
	.leading_digit_separator(true)
	.internal_digit_separator(true)
	.trailing_digit_separator(true)
	.consecutive_digit_separator(false)
	.build();
println!("{:?}", lexical::parse_with_options::<f64, _, FMT>("__1__234__", &opts));

// Ok(1234.0)
```
