### ISSUE TITLE
[BUG] Inconsistent error between int and float parsing

### ISSUE THREAD

**Issue by dubrowgn** [Alexhuszagh/rust-lexical#97]
## Description

While I was writing unit tests to ensure leading and trailing digit separators fail to parse in my program, I noticed a leading separator for floats returns a different error code than the other 3 cases. Instead of `InvalidDigit`, it returns `EmptyMantissa`. For the given input `_12.34`, the mantissa isn't actually empty, but (I assume) the parser never actually gets to parsing it because of the invalid leading separator. While this is a relatively minor issue (the number fails to parse either way), I believe returning `InvalidDigit` is more accurate and consistent, and thus more useful to users.

## Prerequisites

- Rust version: `rustc 1.68.0 (2c8cc3432 2023-03-06)`
- lexical version:
  lexical-util v0.8.5
  lexical-parse-integer v0.8.6
  lexical-parse-float v0.8.5
  lexical-core v0.8.5
  lexical v6.1.1
- Cargo.toml
```toml
[dependencies.lexical]
default-features = false
features = [ "parse-floats", "parse-integers" ]
version = "6.x"

[dependencies.lexical-parse-integer]
default-features = false
features = [ "format", "power-of-two" ]
version = "x"

[dependencies.lexical-parse-float]
default-features = false
features = [ "format", "power-of-two" ]
version = "x"
```

## Test case

```rust
let fopts = lexical::ParseFloatOptions::new();
let iopts = lexical::ParseIntegerOptions::new();
const FMT: u128 = 	NumberFormatBuilder::new()
	.digit_separator(num::NonZeroU8::new(b'_'))
	.build();

println!("int");
println!("{:?}", lexical::parse_with_options::<i64, _, FMT>("_1234", &iopts));
println!("{:?}", lexical::parse_with_options::<i64, _, FMT>("1234_", &iopts));

println!("float");
println!("{:?}", lexical::parse_with_options::<f64, _, FMT>("_12.34", &fopts));
println!("{:?}", lexical::parse_with_options::<f64, _, FMT>("12.34_", &fopts));

// int
// Err(InvalidDigit(0))
// Err(InvalidDigit(4))

// float
// Err(EmptyMantissa(0))
// Err(InvalidDigit(5))
```
